
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 0
	#The name of the modpack
	modpackName = "Create-Delight-Remake"
	#The version of the modpack
	modpackVersion = "v0.4.7.11"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

